# Generated by Django 4.2 on 2023-05-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_pageelement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageElement',
        ),
    ]
